### ISSUE TITLE
[Feature Request] Show all attempts in history

### ISSUE THREAD

**Issue by darewreck54** [temporalio/web#365] opened 2021-07-21 20:11 UTC
**Is your feature request related to a problem? Please describe.**
In the history view, It doesn't show `Attempt 1` and just shows the last successful attempt `Attempt 2`

![image](https://user-images.githubusercontent.com/16171726/126553478-53b17a63-d32c-4ccc-ba77-aa7c9967444c.png)

**Describe the solution you'd like**
Since its a history view, I would expect to have a entry for Attempt 1 of a retry, vs it just showing the last attempt.

**Comment by yiminc** [comment] 2021-07-21 21:12
I think that is by design. It is very possible that an activity could be retried many many times with failure. We don't want to flood the history by all failure attempts. The final attempt is the one that get recorded to history. You should be able to see the failure of previous attempt there as well.

**Comment by feedmeapples** [comment] 2021-07-21 23:15
+ Maxim's comment "While activity is in retry loop you can see the latest failure at the Workflow Summary page or through tctl workflow describe command."

closing as per discussion in slack

**Closed by feedmeapples** 2021-07-21 23:15 UTC
Labels: enhancement
